name: Build and test

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: shirok/setup-gauche@v3
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "8.1"
    - name: Setup mysql
      run: |
        mysql -V
        mysql -uroot -proot < tools/create-test-db-and-user.sql
    - name: Build and check
      run: |
        ./configure
        make
        make -s check
