name: Build and test

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "8.1"
    - name: Setup mysql
      run: |
        mysql -V
        mysql -uroot < tools/create-test-db-and-user.sql
    - uses: shirok/setup-gauche@v5
      with:
        prebuilt-binary: true
    - name: Build and check
      run: |
        ./configure
        make
        #macosx needs this
        if [ -d /Users/runner/hostedtoolcache/ ]; then \
          otool -L dbd_mysql.so; \
        fi
        make -s check
