name: Build and test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: shirok/setup-gauche@v1
    - name: Initialize mysql
      run: |
        sudo service mysql start
        mysql -V
        mysql -uroot -proot < tools/create-test-db-and-user.sql
    - name: Build and check
      run: |
        ./configure
        make
        make -s check
