name: Build and test

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: shirok/setup-gauche@v3
    - name: Setup mysql
      run: |
        if [ "${{ matrix.platform }}" == 'ubuntu-latest' ]; then
          sudo service mysql start
          mysql -V
          mysql -uroot -proot < tools/create-test-db-and-user.sql
        elif [ "${{ matrix.platform }}" == 'macos-latest' ]; then
          brew install mysql
          brew services start mysql
          # mysqld seems to need some time to star up
          sleep 10
          mysql -uroot < tools/create-test-db-and-user.sql
        fi
    - name: Build and check
      run: |
        ./configure
        make
        make -s check
